@echo off
chcp 65001 >nul
cd /d "%~dp0"
echo Initializing git repository...
git init
echo Adding remote...
git remote add origin https://github.com/jnitroun-hue/Pidr_1.01.git
echo Fetching from remote...
git fetch origin main
echo Resetting to remote main...
git reset --soft origin/main
echo Adding changed files...
git add src/app/layout.tsx
echo Committing changes...
git commit -m "Fix: Remove onLoad handler from layout to fix Next.js 15 build error"
echo Pushing to remote...
git push origin HEAD:main
echo Done!
pause

